### ISSUE TITLE
Python and its versions

### ISSUE THREAD

**Issue by mortonjt** [flatironinstitute/disBatch#22]
There are a couple of interesting edge cases that I've noticed when booting this up on another system

1. The shebang in disBatch.py defaults to `/usr/bin/python` which could run into issues if that is Python2. https://github.com/flatironinstitute/disBatch/blob/master/disBatch.py#L1
2. As of [Python>=3.9](https://docs.python.org/3/library/threading.html#threading.Thread.is_alive), `Thread.isAlive()` has changed to `Thread.is_alive()`.  As a result, this line will break for Python>=3.9  https://github.com/flatironinstitute/disBatch/blob/master/disBatch.py#L1053

**Comment by njcarriero** [comment]
Thanks for the suggestions.
Both have been addressed in recent updates.
