### ISSUE TITLE
[Feature Request] task input from command line?

### ISSUE THREAD

**Issue by jingpengw** [flatironinstitute/disBatch#30]
currently, it seems that we need a separate task file for each sbatch run. 
I have many different tasks and it will be hard to manage with a lot of separate task files.
my task is pretty simple and can be expressed with a single line.

Is it possible to input the task as an argument in command line?

This is an example I would like to have.
```bash
sbatch -W -n 128 --cpus-per-task 8 --mem-per-cpu 7g -p ccn --wrap 'disBatch "#DISBATCH REPEAT 1386 (./12_region_graph_arrays.sh)"'
```

**Comment by jingpengw** [comment]
NVM, I just found the `taskcommand` parameter can do the job.

```
sbatch -W -n 128 --cpus-per-task 8 --mem-per-cpu 7g -p ccn --wrap 'disBatch --taskcommand "#DISBATCH REPEAT 1386 (./12_region_graph_arrays.sh)"'
```

**Comment by dylex** [comment]
This is not what `--taskcommand` does; it takes a program that will itself output tasks. But you can just do this:
```
echo '#DISBATCH REPEAT ...' | disBatch -
```

**Comment by jingpengw** [comment]
it also does not work.
the job finishes quickly and did nothing.

**Comment by jingpengw** [comment]
@dylex when I use disBatch in this way, it will not save log files for each task anymore. Is there a way to fetch the log files. I would like to check whether there exist any error or not.

**Comment by dylex** [comment]
disBatch never itself saves log files per task.  It's up to you to redirect the output of tasks to a log file.

**Comment by jingpengw** [comment]
yes, I just figured it out. I need to add some lines.
```
echo "#DISBATCH PREFIX (
#DISBATCH SUFFIX  ) &> \${DISBATCH_NAMETASKS}_\${DISBATCH_JOBID}_\${DISBATCH_TASKID}.log
#DISBATCH REPEAT 2772 ( ./09_split_object_to_fragments.sh )
#DISBATCH SUFFIX  > \${DISBATCH_NAMETASKS}_\${DISBATCH_JOBID}_\${DISBATCH_TASKID}.log
# All engines are idle at this point. Running one last task should trigger retirement(s) of all but one engine.
(echo "running on" $(hostname) ; date ;  )" > Tasks
sbatch -n 4 --cpus-per-task 12 --mem-per-cpu 7g -p ccn --wrap 'disBatch Tasks'
```

**Comment by dylex** [comment]
There's no need to use prefix and suffix (or so many subshells) when you just have a single line. You can just:
```
echo '#DISBATCH REPEAT 2772 ./09_split_object_to_fragments.sh &> ${DISBATCH_NAMETASKS}_${DISBATCH_JOBID}_${DISBATCH_TASKID}.log' ...
```
