### ISSUE TITLE
Pass `--mpi=none` to srun invocation

### ISSUE THREAD

**Issue by dylex** [flatironinstitute/disBatch#31]
This will help ensure MPI tasks don't pick up the outer slurm context.

**Comment by lgarrison** [comment]
We actually already do (via environment variable instead of flag): https://github.com/flatironinstitute/disBatch/blob/b53729a0d6a84ddf8f336d9b831ba5bbd4e2a2aa/disbatchc/disBatch.py#L393

**Comment by dylex** [comment]
Oh, great, I only checked the srun line. Thanks.
