### ISSUE TITLE
Change the save directory of  Logs such as TaskFileName_*_status.txt

### ISSUE THREAD

**Issue by andrewkhardy** [flatironinstitute/disBatch#42]
I am running disBatch on a cluster that treats the $HOME directory has read-only from each compute node. Data and logs must be saved to the $SCRATCH directory and then moved to $PROJECT. 

I am able to specify where logs for each individual job should go, but the disBatch specific logs save to wherever the job was run from. I get the error 

OSError: [Errno 30] Read-only file system: [Long $HOME directory chain]/Scripts/dmrg_12.03.2024_tJ_1D_28_disBatch_241204084502_335_driver.log'

Is there a way to specify where these logs should be saved?

**Comment by lgarrison** [comment]
Yes, `disBatch -p $SCRATCH ...` should work, or `cd $SCRATCH; disBatch ...`.

**Comment by andrewkhardy** [comment]
See the PATH command now...
